spring:
  application:
    name: hapedu-web-api-spring
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hapedu
    username: root
    password: 123456
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: haprab
    password: rablearning

server:
  port: 3535

hapedu:
  security:
    authentication:
      jwt:
        base64-secret: SGFwcHlFZHVjYXRpb25TZWNyZXRrZXlHZW5lcmF0ZWRCeU1pbmhOSA==
        token-validity-in-seconds: 86400
        refresh-token-validity-in-seconds: 604800
        token-validity-in-seconds-for-remember-me: 2592000

springdoc:
  api-docs:
    path: /api-docs

mail:
  username: huuminh0511@gmail.com
  contact-name: noreply@hapedu.com

swagger:
  contact:
    mail: huuminh0511@gmail.com
    name: HapEdu
    url: https://google.com
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/

authentication:
  password:
    default: HappyEdu511!

